plugins { id 'fabric-loom' }

base { archivesName = 'bigbangskills-fabric' }

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
    implementation project(':common')
    implementation project(':persistence-sql')

    implementation 'com.zaxxer:HikariCP:6.2.1'
    include 'com.zaxxer:HikariCP:6.2.1'
    implementation 'org.xerial:sqlite-jdbc:3.46.1.0'
    include 'org.xerial:sqlite-jdbc:3.46.1.0'
    implementation 'com.mysql:mysql-connector-j:9.0.0'
    include 'com.mysql:mysql-connector-j:9.0.0'
    implementation 'org.mariadb.jdbc:mariadb-java-client:3.4.1'
    include 'org.mariadb.jdbc:mariadb-java-client:3.4.1'
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') { expand(version: project.version) }
}

tasks.named('jar', Jar) {
    from project(':api').sourceSets.main.output
    from project(':common').sourceSets.main.output
    from project(':persistence-sql').sourceSets.main.output
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
