allprojects { group = maven_group; version = mod_version }

subprojects {
    apply plugin: 'java-library'

    java {
        toolchain.languageVersion = JavaLanguageVersion.of(21)
        withSourcesJar()
    }

    repositories { mavenCentral() }

    tasks.withType(JavaCompile).configureEach {
        options.release = 21
        options.encoding = 'UTF-8'
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }

    dependencies {
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.11.0'
    }
}
