# source_block|item_id=amount|xp|chance_percent|level
minecraft:mud|minecraft:heart_of_the_sea=1|9999|0.01|90
minecraft:dirt|minecraft:potato=1|50|3.0|10
minecraft:mud|minecraft:potato=1|50|3.0|10
minecraft:mud|minecraft:spyglass=1|500|0.1|7
minecraft:dirt|minecraft:spyglass=1|500|0.1|7
minecraft:mud|minecraft:stick=2|50|2.0|1
minecraft:muddy_mangrove_roots|minecraft:stick=2|50|2.0|1
minecraft:mud|minecraft:feather=3|100|1.0|5
minecraft:clay|minecraft:trident=1|100|0.02|40
minecraft:muddy_mangrove_roots|minecraft:trident=1|100|0.02|40
minecraft:dirt|minecraft:cake=1|3000|0.05|75
minecraft:gravel|minecraft:gunpowder=1|30|10.0|10
minecraft:gravel|minecraft:bone=1|30|10.0|20
minecraft:mud|minecraft:bone=1|30|10.0|20
minecraft:clay|minecraft:slime_ball=1|100|5.0|15
minecraft:clay|minecraft:bucket=1|100|0.1|50
minecraft:gravel|minecraft:netherrack=1|30|0.5|85
minecraft:grass_block|minecraft:apple=1|100|0.1|25
minecraft:clay|minecraft:clock=1|100|0.1|50
minecraft:clay|minecraft:cobweb=1|150|5.0|75
minecraft:clay|minecraft:string=1|200|5.0|25
minecraft:dirt|minecraft:glowstone_dust=1|80|5.0|5
minecraft:sand|minecraft:glowstone_dust=1|80|5.0|5
minecraft:dirt|minecraft:diamond=1|1000|0.13|35
minecraft:mud|minecraft:diamond=1|1000|0.13|35
minecraft:dirt|minecraft:cocoa_beans=1|100|1.33|35
minecraft:mud|minecraft:cocoa_beans=1|100|1.33|35
minecraft:dirt|minecraft:quartz=1|100|0.5|85
minecraft:dirt|minecraft:name_tag=1|3000|0.05|25
