# mcMMO Bonus_Drops.Mining defaults.
minecraft:amethyst_cluster=true
minecraft:andesite=true
minecraft:ancient_debris=true
minecraft:basalt=true
minecraft:blackstone=true
minecraft:amethyst_block=true
minecraft:budding_amethyst=true
minecraft:calcite=true
minecraft:chain=true
minecraft:chiseled_nether_bricks=true
minecraft:coal_ore=true
minecraft:cobbled_deepslate=true
minecraft:cracked_nether_bricks=true
minecraft:crying_obsidian=true
minecraft:copper_ore=true
minecraft:deepslate=true
minecraft:deepslate_coal_ore=true
minecraft:deepslate_copper_ore=true
minecraft:deepslate_diamond_ore=true
minecraft:deepslate_emerald_ore=true
minecraft:deepslate_gold_ore=true
minecraft:deepslate_iron_ore=true
minecraft:deepslate_lapis_ore=true
minecraft:deepslate_redstone_ore=true
minecraft:diamond_ore=true
minecraft:diorite=true
minecraft:emerald_ore=true
minecraft:end_stone=true
minecraft:glowstone=true
minecraft:gilded_blackstone=true
minecraft:gold_ore=true
minecraft:granite=true
minecraft:iron_ore=true
minecraft:lapis_ore=true
minecraft:mossy_cobblestone=true
minecraft:nether_bricks=true
minecraft:nether_gold_ore=true
minecraft:nether_quartz_ore=true
minecraft:netherrack=true
minecraft:obsidian=true
minecraft:polished_basalt=true
minecraft:red_nether_bricks=true
minecraft:redstone_ore=true
minecraft:sandstone=true
minecraft:small_amethyst_bud=true
minecraft:medium_amethyst_bud=true
minecraft:large_amethyst_bud=true
minecraft:smooth_basalt=true
minecraft:stone=true
minecraft:tuff=true
minecraft:warped_nylium=true
minecraft:crimson_nylium=true
