# item_id=repair_xp_category
minecraft:shield=wood
minecraft:wooden_sword=wood
minecraft:wooden_shovel=wood
minecraft:wooden_pickaxe=wood
minecraft:wooden_axe=wood
minecraft:wooden_hoe=wood
minecraft:stone_sword=stone
minecraft:stone_shovel=stone
minecraft:stone_pickaxe=stone
minecraft:stone_axe=stone
minecraft:stone_hoe=stone
minecraft:copper_sword=copper
minecraft:copper_shovel=copper
minecraft:copper_pickaxe=copper
minecraft:copper_axe=copper
minecraft:copper_hoe=copper
minecraft:copper_helmet=copper
minecraft:copper_chestplate=copper
minecraft:copper_leggings=copper
minecraft:copper_boots=copper
minecraft:iron_sword=iron
minecraft:iron_shovel=iron
minecraft:iron_pickaxe=iron
minecraft:iron_axe=iron
minecraft:iron_hoe=iron
minecraft:iron_helmet=iron
minecraft:iron_chestplate=iron
minecraft:iron_leggings=iron
minecraft:iron_boots=iron
minecraft:golden_sword=gold
minecraft:golden_shovel=gold
minecraft:golden_pickaxe=gold
minecraft:golden_axe=gold
minecraft:golden_hoe=gold
minecraft:golden_helmet=gold
minecraft:golden_chestplate=gold
minecraft:golden_leggings=gold
minecraft:golden_boots=gold
minecraft:diamond_sword=diamond
minecraft:diamond_shovel=diamond
minecraft:diamond_pickaxe=diamond
minecraft:diamond_axe=diamond
minecraft:diamond_hoe=diamond
minecraft:diamond_helmet=diamond
minecraft:diamond_chestplate=diamond
minecraft:diamond_leggings=diamond
minecraft:diamond_boots=diamond
minecraft:netherite_sword=netherite
minecraft:netherite_shovel=netherite
minecraft:netherite_pickaxe=netherite
minecraft:netherite_axe=netherite
minecraft:netherite_hoe=netherite
minecraft:netherite_helmet=netherite
minecraft:netherite_chestplate=netherite
minecraft:netherite_leggings=netherite
minecraft:netherite_boots=netherite
minecraft:leather_helmet=leather
minecraft:leather_chestplate=leather
minecraft:leather_leggings=leather
minecraft:leather_boots=leather
minecraft:bow=string
minecraft:crossbow=string
minecraft:fishing_rod=string
minecraft:carrot_on_a_stick=string
minecraft:warped_fungus_on_a_stick=string
minecraft:shears=iron
minecraft:flint_and_steel=iron
minecraft:elytra=other
minecraft:trident=other
minecraft:mace=other
