# item_id=result_id|maximum_quantity|maximum_durability|minimum_level
minecraft:wooden_sword=minecraft:stick|2|59|0
minecraft:stone_sword=minecraft:cobblestone|2|131|0
minecraft:iron_sword=minecraft:iron_ingot|2|250|0
minecraft:golden_sword=minecraft:gold_ingot|2|32|0
minecraft:diamond_sword=minecraft:diamond|2|1561|50
minecraft:netherite_sword=minecraft:netherite_ingot|4|2031|100
minecraft:wooden_pickaxe=minecraft:stick|3|59|0
minecraft:stone_pickaxe=minecraft:cobblestone|3|131|0
minecraft:iron_pickaxe=minecraft:iron_ingot|3|250|0
minecraft:golden_pickaxe=minecraft:gold_ingot|3|32|0
minecraft:diamond_pickaxe=minecraft:diamond|3|1561|50
minecraft:netherite_pickaxe=minecraft:netherite_ingot|4|2031|100
minecraft:wooden_axe=minecraft:stick|3|59|0
minecraft:stone_axe=minecraft:cobblestone|3|131|0
minecraft:iron_axe=minecraft:iron_ingot|3|250|0
minecraft:golden_axe=minecraft:gold_ingot|3|32|0
minecraft:diamond_axe=minecraft:diamond|3|1561|50
minecraft:netherite_axe=minecraft:netherite_ingot|4|2031|100
minecraft:wooden_shovel=minecraft:stick|1|59|0
minecraft:stone_shovel=minecraft:cobblestone|1|131|0
minecraft:iron_shovel=minecraft:iron_ingot|1|250|0
minecraft:golden_shovel=minecraft:gold_ingot|1|32|0
minecraft:diamond_shovel=minecraft:diamond|1|1561|50
minecraft:netherite_shovel=minecraft:netherite_ingot|4|2031|100
minecraft:wooden_hoe=minecraft:stick|2|59|0
minecraft:stone_hoe=minecraft:cobblestone|2|131|0
minecraft:iron_hoe=minecraft:iron_ingot|2|250|0
minecraft:golden_hoe=minecraft:gold_ingot|2|32|0
minecraft:diamond_hoe=minecraft:diamond|2|1561|50
minecraft:netherite_hoe=minecraft:netherite_ingot|4|2031|100
minecraft:iron_helmet=minecraft:iron_ingot|5|165|0
minecraft:iron_chestplate=minecraft:iron_ingot|8|240|0
minecraft:iron_leggings=minecraft:iron_ingot|7|225|0
minecraft:iron_boots=minecraft:iron_ingot|4|195|0
minecraft:golden_helmet=minecraft:gold_ingot|5|77|0
minecraft:golden_chestplate=minecraft:gold_ingot|8|112|0
minecraft:golden_leggings=minecraft:gold_ingot|7|105|0
minecraft:golden_boots=minecraft:gold_ingot|4|91|0
minecraft:diamond_helmet=minecraft:diamond|5|363|50
minecraft:diamond_chestplate=minecraft:diamond|8|528|50
minecraft:diamond_leggings=minecraft:diamond|7|495|50
minecraft:diamond_boots=minecraft:diamond|4|429|50
minecraft:netherite_helmet=minecraft:netherite_ingot|4|407|100
minecraft:netherite_chestplate=minecraft:netherite_ingot|4|592|100
minecraft:netherite_leggings=minecraft:netherite_ingot|4|555|100
minecraft:netherite_boots=minecraft:netherite_ingot|4|481|100
minecraft:leather_helmet=minecraft:leather|5|55|0
minecraft:leather_chestplate=minecraft:leather|8|80|0
minecraft:leather_leggings=minecraft:leather|7|75|0
minecraft:leather_boots=minecraft:leather|4|65|0
minecraft:bow=minecraft:string|1|384|0
minecraft:crossbow=minecraft:string|1|465|0
minecraft:fishing_rod=minecraft:string|1|64|0
minecraft:carrot_on_a_stick=minecraft:string|1|25|0
minecraft:shears=minecraft:iron_ingot|1|238|0
minecraft:flint_and_steel=minecraft:iron_ingot|1|64|0
minecraft:trident=minecraft:prismarine_shard|1|250|0
