# mcMMO Bonus_Drops.Woodcutting defaults.
minecraft:acacia_log=true
minecraft:acacia_wood=true
minecraft:birch_log=true
minecraft:birch_wood=true
minecraft:cherry_log=true
minecraft:cherry_wood=true
minecraft:crimson_hyphae=true
minecraft:crimson_roots=true
minecraft:crimson_stem=true
minecraft:dark_oak_log=true
minecraft:dark_oak_wood=true
minecraft:jungle_log=true
minecraft:jungle_wood=true
minecraft:mangrove_log=true
minecraft:mangrove_wood=true
minecraft:oak_log=true
minecraft:oak_wood=true
minecraft:pale_oak_log=true
minecraft:pale_oak_wood=true
minecraft:shroomlight=true
minecraft:spruce_log=true
minecraft:spruce_wood=true
minecraft:stripped_crimson_hyphae=true
minecraft:stripped_warped_hyphae=true
minecraft:warped_hyphae=true
minecraft:warped_roots=true
minecraft:warped_stem=true
